version: '3.9'
services:
  web:
    build: ./
    container_name: 'unisoft'
    restart :  always
    volumes: 
      - .:/uzb
    ports:
      - "8081:8081"
    env_file:
      - ./.env 
    command: sh -c "python manage.py runserver 0.0.0.0:8003"