# Generated by Django 5.0.4 on 2024-04-23 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ext_id', models.IntegerField(default=0)),
                ('ref_name', models.CharField(max_length=250)),
                ('cardnumber', models.CharField(max_length=16)),
                ('commision', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('currency', models.IntegerField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
